### ISSUE TITLE
[Request] Enable CDDA audio emulation

### ISSUE THREAD

**Issue by cucholix** [Mystro256/wiisxr#64] opened 2017-10-03 02:00 UTC
CDDA audio emulation appears grayed out, I wonder if it was disabled on original Wii to save processing cycles, if it's already implemented would be possible enable it for Wii U? vWii in 1.2ghz mode.

**Comment by roflcopter777** [comment] 2017-10-03 02:01
It was, but since the vWii has been unlocked, it can be turned on. Whether it will or not remains to be seen, people tried to find out in the source code, but there aren't any leads.

**Comment by Mystro256** [comment] 2017-10-03 19:06
Duplicate of #43 , Closing

**Closed as completed by Mystro256** 2017-10-03 19:06 UTC
